[mgr]
cwd           = { fg = "#7aa2f7" }
border_symbol = " "

[indicator]
current = { bg = "#2c2c3c" }

[filetype]

rules = [
	{ url = "*",  is = "orphan", fg = "red" },
	{ url = "*",  is = "link",   fg = "cyan" },
	{ url = "*/", is = "link",   fg = "cyan" },
	{ url = "*",  is = "exec",   fg = "green" },
	{ url = "*/",                fg = "#7aa2f7" },
]

[icon]

conds = [
	{ if = "orphan", text = "", fg = "red" },
	{ if = "link",   text = "", fg = "cyan" },
	{ if = "dir",    text = "", fg = "#7aa2f7" },
	{ if = "exec",   text = "", fg = "green" },
	{ if = "!dir",   text = ""               },
]
