format = "($battery)($sudo)($username)(${custom.inside_home})(${custom.inside_symlink})($directory)(${custom.space})($git_branch)($git_status)($cmd_duration)($status)($character)"
add_newline = false
command_timeout = 60000

[directory]
home_symbol = ""
truncation_length = 9
format = '[$path](bold fg:#5555cc)[$read_only]($read_only_style)'

[custom.inside_home]
when = """ ! git rev-parse --is-inside-work-tree && pwd | grep --ignore-case "$HOME/" """
format = "[~](bold fg:#5555cc)"

[custom.inside_symlink]
when = """ git rev-parse --is-inside-work-tree && [[ "$PWD:A" != "$PWD" ]]"""
format = "[~](bold fg:#5555cc)"

[custom.space]
when = """ test "${HOME:l}" != "${PWD:l}" """
format = " "

[cmd_duration]
min_time = 60000

[character] # The name of the module we are configuring is "character"
# success_symbol = "[󰞷 ](bold green)" # zsh.exe's vim-mode crashes on long lines due to `󰞷` (is not unicode) inside msys2
success_symbol = "[ ](bold green)"
error_symbol = "[ ](bold red)"
vimcmd_symbol =	"[ ](bold green)"
vimcmd_replace_one_symbol =	"[ ](bold purple)"
vimcmd_replace_symbol =	"[ ](bold purple)"
vimcmd_visual_symbol =	"[ ](bold yellow)"
format = "$symbol"
