name: Upload_Release

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# https://josh-ops.com/posts/gh-auth-login-in-actions/
# https://stackoverflow.com/questions/76830110/github-cli-from-github-actions-workflow
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#secrets-context
# Since `VSCE_TOKEN` is a secret variable, it is not immediately usable as an environment variable. see: https://github.com/microsoft/vscode-docs/pull/3857
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # setting GH_TOKEN for the entire workflow
  VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
  OVSX_PAT: ${{ secrets.OVSX_TOKEN }}

# https://github.com/googleapis/release-please-action?tab=readme-ov-file#workflow-permissions
# GitHub requires `issues: write` permission for label management since labels are shared between issues and pull requests
# https://github.com/googleapis/release-please-action/issues/1070 <-> release-please failed Resource not accessible by integration
# https://github.com/cli/cli/issues/9514                          <-> release-please failed Resource not accessible by integration
permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write # Required for PyPI/npm Trusted Publishing (OIDC)
  # workflows: write

jobs:
  # https://www.youtube.com/watch?v=P0wAXh5UOnM
  #                                                      ╭────────────────────────────────────────────────────────────────────────────────────────────────────────╮
  # to retrigger remove the github release, tag then --> │ git pull --rebase --> lazygit remove github-action commit and ammend your changes --> git push --force │
  #                                                      ╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

  vscode-marketplace:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    environment: vscode-marketplace
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - run: npm install

      - run: yes | npx vsce package

      - name: Publish to vscode-marketplace 🚀
        run: yes | npx vsce publish

      - name: Publish to open-vsx 🚀
        run: yes | npx ovsx publish

      - name: Github vsix release 📦
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} *.vsix

